#!/usr/bin/env python3
"""
Generate TTS audio for go-ot-security video using Google Cloud TTS.

Usage:
    python generate-audio-gcloud.py          # Japanese only (default)
    python generate-audio-gcloud.py en       # English only
    python generate-audio-gcloud.py en ja    # Both
"""

import base64
import json
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ID = os.environ.get("GCLOUD_PROJECT_ID", "dashai-490610")
API_URL = "https://texttospeech.googleapis.com/v1/text:synthesize"
FPS = 30

VOICE_MAP = {
    "en": ("en-US", "en-US-Neural2-D"),
    "ja": ("ja-JP", "ja-JP-Neural2-D"),
}

REMOTION = Path(__file__).parent
VIDEO_DIR = REMOTION.parent


def read_narration(locale: str) -> list[dict]:
    tsv_file = VIDEO_DIR / f"narration.otsec.{locale}.tsv"
    if not tsv_file.exists():
        print(f"  Missing: {tsv_file}")
        return []
    scenes = []
    idx = 1
    for line in tsv_file.read_text().strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            continue
        scene_id, text = parts
        scenes.append({
            "id": f"{idx:02d}-{scene_id}",
            "scene": scene_id,
            "title": scene_id.replace("ot-", "").replace("-", " ").title(),
            "text": text.strip(),
        })
        idx += 1
    return scenes


def get_token() -> str:
    result = subprocess.run(
        ["gcloud", "auth", "print-access-token"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise Exception("gcloud auth failed. Run: gcloud auth login")
    return result.stdout.strip()


def get_duration(file_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(file_path)],
        capture_output=True, text=True,
    )
    return float(result.stdout.strip()) if result.stdout.strip() else 0


def synthesize(scene: dict, locale: str, token: str, output_dir: Path) -> dict:
    lang_code, voice_name = VOICE_MAP[locale]
    output_file = output_dir / f"{scene['id']}.mp3"

    if output_file.exists() and output_file.stat().st_size > 0:
        duration = get_duration(output_file)
        frames = round((duration + 0.8) * FPS)
        print(f"  {scene['id']}: exists ({duration:.2f}s, {frames} frames)")
        return {"id": scene["id"], "scene": scene["scene"], "title": scene["title"],
                "file": f"{scene['id']}.mp3", "duration": duration, "frames": frames}

    import requests
    headers = {
        "Authorization": f"Bearer {token}",
        "x-goog-user-project": PROJECT_ID,
        "Content-Type": "application/json",
    }
    payload = {
        "input": {"text": scene["text"]},
        "voice": {"languageCode": lang_code, "name": voice_name},
        "audioConfig": {"audioEncoding": "MP3", "speakingRate": 0.95, "pitch": -1.0},
    }
    resp = requests.post(API_URL, headers=headers, json=payload, timeout=60)
    if resp.status_code != 200:
        raise Exception(f"TTS error ({resp.status_code}): {resp.text[:200]}")

    audio_bytes = base64.b64decode(resp.json()["audioContent"])
    output_file.write_bytes(audio_bytes)

    duration = get_duration(output_file)
    frames = round((duration + 0.8) * FPS)
    print(f"  {scene['id']}: generated ({duration:.2f}s, {frames} frames)")
    return {"id": scene["id"], "scene": scene["scene"], "title": scene["title"],
            "file": f"{scene['id']}.mp3", "duration": duration, "frames": frames}


def write_config(results: list[dict], locale: str):
    scenes_lines = []
    for r in results:
        scenes_lines.append(f'''  {{
    id: "{r['id']}",
    scene: "{r['scene']}",
    title: "{r['title']}",
    durationInFrames: {r['frames']},
    audioFile: "{r['file']}",
  }}''')

    scenes_content = ",\n".join(scenes_lines)
    content = f'''// Auto-generated by generate-audio-gcloud.py — do not edit
export interface SceneConfig {{
  id: string;
  scene: string;
  title: string;
  durationInFrames: number;
  audioFile: string;
}}

export const SCENES: SceneConfig[] = [
{scenes_content},
];

export function getSceneStart(sceneIndex: number): number {{
  return SCENES.slice(0, sceneIndex).reduce((sum, s) => sum + s.durationInFrames, 0);
}}

export const TOTAL_FRAMES = SCENES.reduce((sum, s) => sum + s.durationInFrames, 0) + 30;
export const FPS = {FPS};
'''
    config_file = REMOTION / "src" / f"audioConfig.otsec.{locale}.ts"
    config_file.write_text(content)
    print(f"  Config: {config_file}")


def main():
    locales = sys.argv[1:] if len(sys.argv) > 1 else ["ja"]
    token = get_token()

    for locale in locales:
        if locale not in VOICE_MAP:
            print(f"  Unknown locale: {locale}")
            continue

        print(f"\n=== go-ot-security Video ({locale} - Google Cloud TTS) ===")
        scenes = read_narration(locale)
        if not scenes:
            continue

        output_dir = REMOTION / "public" / "audio" / f"otsec-{locale}"
        output_dir.mkdir(parents=True, exist_ok=True)

        results = []
        for scene in scenes:
            result = synthesize(scene, locale, token, output_dir)
            results.append(result)

        write_config(results, locale)

        total_sec = sum(r["duration"] for r in results)
        total_frames = sum(r["frames"] for r in results)
        print(f"  Total: {total_sec:.1f}s, {total_frames} frames")

    print("\nDone. Run: npm run render:otsec-en / npm run render:otsec-ja")


if __name__ == "__main__":
    main()
