#!/usr/bin/env python3
"""
Generate TTS audio for go-ot-security video (English) using ElevenLabs API.

Usage:
    python generate-audio-elevenlabs.py
    python generate-audio-elevenlabs.py --voice-id <id>

Requires: ELEVENLABS_API_KEY environment variable
"""

import json
import os
import subprocess
import sys
from pathlib import Path

API_KEY = os.environ.get("ELEVENLABS_API_KEY")
API_URL = "https://api.elevenlabs.io/v1/text-to-speech"
# Default: "Adam" — professional male voice
DEFAULT_VOICE_ID = "pNInz6obpgDQGcFmaJgB"
FPS = 30

REMOTION = Path(__file__).parent
VIDEO_DIR = REMOTION.parent


def read_narration() -> list[dict]:
    tsv_file = VIDEO_DIR / "narration.otsec.en.tsv"
    if not tsv_file.exists():
        print(f"  Missing: {tsv_file}")
        return []
    scenes = []
    idx = 1
    for line in tsv_file.read_text().strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            continue
        scene_id, text = parts
        scenes.append({
            "id": f"{idx:02d}-{scene_id}",
            "scene": scene_id,
            "title": scene_id.replace("ot-", "").replace("-", " ").title(),
            "text": text.strip(),
        })
        idx += 1
    return scenes


def get_duration(file_path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(file_path)],
        capture_output=True, text=True,
    )
    return float(result.stdout.strip()) if result.stdout.strip() else 0


def synthesize(scene: dict, voice_id: str, output_dir: Path) -> dict:
    output_file = output_dir / f"{scene['id']}.mp3"

    if output_file.exists() and output_file.stat().st_size > 0:
        duration = get_duration(output_file)
        frames = round((duration + 0.8) * FPS)
        print(f"  {scene['id']}: exists ({duration:.2f}s, {frames} frames)")
        return {"id": scene["id"], "scene": scene["scene"], "title": scene["title"],
                "file": f"{scene['id']}.mp3", "duration": duration, "frames": frames}

    import requests
    url = f"{API_URL}/{voice_id}"
    headers = {
        "xi-api-key": API_KEY,
        "Content-Type": "application/json",
        "Accept": "audio/mpeg",
    }
    payload = {
        "text": scene["text"],
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.75,
            "style": 0.2,
            "use_speaker_boost": True,
        },
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=60)
    if resp.status_code != 200:
        raise Exception(f"ElevenLabs error ({resp.status_code}): {resp.text[:200]}")

    output_file.write_bytes(resp.content)

    duration = get_duration(output_file)
    frames = round((duration + 0.8) * FPS)
    print(f"  {scene['id']}: generated ({duration:.2f}s, {frames} frames)")
    return {"id": scene["id"], "scene": scene["scene"], "title": scene["title"],
            "file": f"{scene['id']}.mp3", "duration": duration, "frames": frames}


def write_config(results: list[dict]):
    scenes_lines = []
    for r in results:
        scenes_lines.append(f'''  {{
    id: "{r['id']}",
    scene: "{r['scene']}",
    title: "{r['title']}",
    durationInFrames: {r['frames']},
    audioFile: "{r['file']}",
  }}''')

    scenes_content = ",\n".join(scenes_lines)
    content = f'''// Auto-generated by generate-audio-elevenlabs.py — do not edit
export interface SceneConfig {{
  id: string;
  scene: string;
  title: string;
  durationInFrames: number;
  audioFile: string;
}}

export const SCENES: SceneConfig[] = [
{scenes_content},
];

export function getSceneStart(sceneIndex: number): number {{
  return SCENES.slice(0, sceneIndex).reduce((sum, s) => sum + s.durationInFrames, 0);
}}

export const TOTAL_FRAMES = SCENES.reduce((sum, s) => sum + s.durationInFrames, 0) + 30;
export const FPS = {FPS};
'''
    config_file = REMOTION / "src" / "audioConfig.otsec.en.ts"
    config_file.write_text(content)
    print(f"  Config: {config_file}")


def main():
    if not API_KEY:
        print("Error: ELEVENLABS_API_KEY not set")
        sys.exit(1)

    voice_id = DEFAULT_VOICE_ID
    if "--voice-id" in sys.argv:
        idx = sys.argv.index("--voice-id")
        if idx + 1 < len(sys.argv):
            voice_id = sys.argv[idx + 1]

    print(f"\n=== go-ot-security Video (EN - ElevenLabs) ===")
    print(f"  Voice ID: {voice_id}")
    scenes = read_narration()
    if not scenes:
        return

    output_dir = REMOTION / "public" / "audio" / "otsec-en"
    output_dir.mkdir(parents=True, exist_ok=True)

    results = []
    for scene in scenes:
        result = synthesize(scene, voice_id, output_dir)
        results.append(result)

    write_config(results)

    total_sec = sum(r["duration"] for r in results)
    total_frames = sum(r["frames"] for r in results)
    print(f"  Total: {total_sec:.1f}s, {total_frames} frames")
    print("\nDone. Run: npm run render:otsec-en")


if __name__ == "__main__":
    main()
