// Auto-generated by generate-audio-gcloud.py — do not edit
export interface SceneConfig {
  id: string;
  scene: string;
  title: string;
  durationInFrames: number;
  audioFile: string;
}

export const SCENES: SceneConfig[] = [
  {
    id: "01-ot-hook",
    scene: "ot-hook",
    title: "Hook",
    durationInFrames: 467,
    audioFile: "01-ot-hook.mp3",
  },
  {
    id: "02-ot-discovery",
    scene: "ot-discovery",
    title: "Discovery",
    durationInFrames: 542,
    audioFile: "02-ot-discovery.mp3",
  },
  {
    id: "03-ot-monitor",
    scene: "ot-monitor",
    title: "Monitor",
    durationInFrames: 478,
    audioFile: "03-ot-monitor.mp3",
  },
  {
    id: "04-ot-dashboard",
    scene: "ot-dashboard",
    title: "Dashboard",
    durationInFrames: 715,
    audioFile: "04-ot-dashboard.mp3",
  },
  {
    id: "05-ot-cta",
    scene: "ot-cta",
    title: "Cta",
    durationInFrames: 562,
    audioFile: "05-ot-cta.mp3",
  },
];

export function getSceneStart(sceneIndex: number): number {
  return SCENES.slice(0, sceneIndex).reduce((sum, s) => sum + s.durationInFrames, 0);
}

export const TOTAL_FRAMES = SCENES.reduce((sum, s) => sum + s.durationInFrames, 0) + 30;
export const FPS = 30;
